use shamrocq_compiler::codegen::compile_program;
use shamrocq_compiler::desugar::desugar_program;
use shamrocq_compiler::parser::parse;
use shamrocq_compiler::resolve::{resolve_program, GlobalTable, TagTable};

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let scheme_path = format!("{}/../../fourchette.scm", manifest_dir);

    println!("cargo:rerun-if-changed={}", scheme_path);

    let src = std::fs::read_to_string(&scheme_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {}", scheme_path, e));

    let sexps = parse(&src).unwrap_or_else(|e| panic!("parse error: {}", e));
    let defs = desugar_program(&sexps).unwrap_or_else(|e| panic!("desugar error: {}", e));

    let mut tags = TagTable::new();
    let mut globals = GlobalTable::new();
    let rdefs = resolve_program(&defs, &mut tags, &mut globals)
        .unwrap_or_else(|e| panic!("resolve error: {}", e));

    let prog = compile_program(&rdefs);
    let blob = prog.serialize();

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let bytecode_path = format!("{}/bytecode.bin", out_dir);
    std::fs::write(&bytecode_path, &blob).unwrap();

    // Generate a tags module with constants for global function indices.
    let mut tags_src = String::from("// Auto-generated by build.rs\n");
    for (i, (name, _offset)) in prog.header.globals.iter().enumerate() {
        let const_name = name.to_uppercase();
        tags_src.push_str(&format!("pub const {}: u16 = {};\n", const_name, i));
    }
    let funcs_path = format!("{}/funcs.rs", out_dir);
    std::fs::write(&funcs_path, &tags_src).unwrap();

    eprintln!(
        "shamrocq: compiled {} globals, {} bytes of bytecode",
        prog.header.n_globals,
        blob.len()
    );
}
