fn main() {
    #[cfg(feature = "integration")]
    integration::compile();
}

#[cfg(feature = "integration")]
mod integration {
    use shamrocq_compiler::codegen::compile_program;
    use shamrocq_compiler::desugar::desugar_program;
    use shamrocq_compiler::parser::parse;
    use shamrocq_compiler::resolve::{resolve_program, GlobalTable, TagTable};

    pub fn compile() {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        let root = format!("{}/../../", manifest_dir);
        let scheme_dir = format!("{}scheme", root);

        println!("cargo:rerun-if-changed={}", scheme_dir);

        let mut paths: Vec<_> = std::fs::read_dir(&scheme_dir)
            .unwrap_or_else(|e| panic!("cannot read scheme dir {}: {}", scheme_dir, e))
            .filter_map(|entry| {
                let entry = entry.ok()?;
                let path = entry.path();
                let name = path.file_name()?.to_str()?;
                if path.extension().and_then(|e| e.to_str()) == Some("scm")
                    && name != "macros_extr.scm"
                {
                    Some(path)
                } else {
                    None
                }
            })
            .collect();
        paths.sort();

        let mut all_sexps = Vec::new();
        for path in &paths {
            let path_str = path.display().to_string();
            println!("cargo:rerun-if-changed={}", path_str);
            let src = std::fs::read_to_string(path)
                .unwrap_or_else(|e| panic!("cannot read {}: {}", path_str, e));
            let sexps =
                parse(&src).unwrap_or_else(|e| panic!("parse error in {}: {}", path_str, e));
            all_sexps.extend(sexps);
        }

        let defs =
            desugar_program(&all_sexps).unwrap_or_else(|e| panic!("desugar error: {}", e));

        let mut tags = TagTable::new();
        let mut globals = GlobalTable::new();
        let rdefs = resolve_program(&defs, &mut tags, &mut globals)
            .unwrap_or_else(|e| panic!("resolve error: {}", e));

        let prog = compile_program(&rdefs);
        let blob = prog.serialize();

        let out_dir = std::env::var("OUT_DIR").unwrap();
        let bytecode_path = format!("{}/bytecode.bin", out_dir);
        std::fs::write(&bytecode_path, &blob).unwrap();

        let mut funcs_src = String::from("// Auto-generated by build.rs\n");
        for (i, (name, _offset)) in prog.header.globals.iter().enumerate() {
            let const_name = name.to_uppercase();
            funcs_src.push_str(&format!("pub const {}: u16 = {};\n", const_name, i));
        }
        let funcs_path = format!("{}/funcs.rs", out_dir);
        std::fs::write(&funcs_path, &funcs_src).unwrap();

        let mut ctors_src = String::from("// Auto-generated by build.rs\n");
        for (name, id) in tags.entries() {
            let const_name = name.to_uppercase();
            ctors_src.push_str(&format!("pub const {}: u8 = {};\n", const_name, id));
        }
        let ctors_path = format!("{}/ctors.rs", out_dir);
        std::fs::write(&ctors_path, &ctors_src).unwrap();

        eprintln!(
            "shamrocq: compiled {} globals, {} ctors, {} bytes of bytecode ({} scheme files)",
            prog.header.n_globals,
            tags.entries().len(),
            blob.len(),
            paths.len(),
        );
    }
}
