use std::path::PathBuf;

use clap::Parser;

use shamrocq_compiler::codegen::compile_program;
use shamrocq_compiler::desugar::desugar_program;
use shamrocq_compiler::parser::parse;
use shamrocq_compiler::resolve::{resolve_program, GlobalTable, TagTable};

/// Compile Scheme files into shamrocq bytecode for bare-metal execution.
#[derive(Parser)]
#[command(name = "shamrocq-compiler", version)]
struct Cli {
    /// Output directory for generated files
    #[arg(short, long, default_value = ".")]
    output: PathBuf,

    /// Scheme source files to compile
    #[arg(required = true)]
    files: Vec<PathBuf>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();

    let mut all_sexps = Vec::new();
    for path in &cli.files {
        let src = std::fs::read_to_string(path)
            .map_err(|e| format!("cannot read {}: {}", path.display(), e))?;
        let sexps =
            parse(&src).map_err(|e| format!("parse error in {}: {}", path.display(), e))?;
        all_sexps.extend(sexps);
    }

    let defs = desugar_program(&all_sexps).map_err(|e| format!("desugar: {}", e))?;

    let mut tags = TagTable::new();
    let mut globals = GlobalTable::new();
    let rdefs =
        resolve_program(&defs, &mut tags, &mut globals).map_err(|e| format!("resolve: {}", e))?;

    let prog = compile_program(&rdefs);
    let blob = prog.serialize();

    std::fs::create_dir_all(&cli.output)?;

    let bytecode_path = cli.output.join("bytecode.bin");
    std::fs::write(&bytecode_path, &blob)?;

    let mut funcs_src = String::from("// Auto-generated by shamrocq-compiler\n");
    for (i, (name, _offset)) in prog.header.globals.iter().enumerate() {
        funcs_src.push_str(&format!("pub const {}: u16 = {};\n", name.to_uppercase(), i));
    }
    let funcs_path = cli.output.join("funcs.rs");
    std::fs::write(&funcs_path, &funcs_src)?;

    let mut ctors_src = String::from("// Auto-generated by shamrocq-compiler\n");
    for (name, id) in tags.entries() {
        ctors_src.push_str(&format!("pub const {}: u8 = {};\n", name.to_uppercase(), id));
    }
    let ctors_path = cli.output.join("ctors.rs");
    std::fs::write(&ctors_path, &ctors_src)?;

    let mut foreign_fns_src = String::from("// Auto-generated by shamrocq-compiler\n");
    for (name, idx) in &prog.foreign_fns {
        foreign_fns_src.push_str(&format!("pub const {}: u16 = {};\n", name.to_uppercase(), idx));
    }
    let foreign_fns_path = cli.output.join("foreign_fns.rs");
    std::fs::write(&foreign_fns_path, &foreign_fns_src)?;

    eprintln!(
        "compiled {} globals, {} ctors, {} foreign fns, {} bytes of bytecode from {} files",
        prog.header.n_globals,
        tags.entries().len(),
        prog.foreign_fns.len(),
        blob.len(),
        cli.files.len(),
    );
    eprintln!("  -> {}", bytecode_path.display());
    eprintln!("  -> {}", funcs_path.display());
    eprintln!("  -> {}", ctors_path.display());
    eprintln!("  -> {}", foreign_fns_path.display());

    Ok(())
}
